server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates: Path=/account/**
        - id: auth-service
          uri: lb://auth-service
          predicates: Path=/auth/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates: Path=/catalog/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates: Path=/delivery/**
        - id: order-service
          uri: lb://order-service
          predicates: Path=/order/**
        - id: shopping-cart-service
          uri: lb://shopping-cart-service
          predicates:
            - Path=/shopping-cart/**
            - Path=/cart/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
